import { useState } from 'react';
import { FileText, Users, Sparkles, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ReportCard } from '@/components/reports/ReportCard';
import { ReportViewerModal } from '@/components/reports/ReportViewerModal';
import { useReports, useMarkReportAsRead, useDeleteReport, type Report } from '@/hooks/useReports';
import { toast } from 'sonner';

export const ReportsPage = () => {
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [activeTab, setActiveTab] = useState<'employee' | 'insight'>('employee');

  const { data: employeeReports = [], isLoading: loadingEmployee } = useReports('employee');
  const { data: insightReports = [], isLoading: loadingInsight } = useReports('insight');
  const markAsRead = useMarkReportAsRead();
  const deleteReport = useDeleteReport();

  const handleViewReport = (report: Report) => {
    setSelectedReport(report);
    if (!report.is_read) markAsRead.mutate(report.id);
  };

  const handleDeleteReport = (reportId: string) => {
    deleteReport.mutate(reportId, {
      onSuccess: () => toast.success('Report deleted'),
      onError: () => toast.error('Failed to delete report'),
    });
  };

  const reports = activeTab === 'employee' ? employeeReports : insightReports;
  const isLoading = activeTab === 'employee' ? loadingEmployee : loadingInsight;

  const unreadEmployeeCount = employeeReports.filter(r => !r.is_read).length;
  const unreadInsightCount = insightReports.filter(r => !r.is_read).length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <div className="p-3 rounded-xl bg-gradient-to-br from-primary/20 to-primary/5">
          <FileText className="h-8 w-8 text-primary" />
        </div>
        <div>
          <h1 className="text-3xl font-orbitron font-bold text-glow">Reports & Insights</h1>
          <p className="text-muted-foreground font-exo">View HTML reports generated by your AI agents</p>
        </div>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as typeof activeTab)}>
        <TabsList className="bg-card/50 border border-border/50 p-1">
          <TabsTrigger value="employee" className="gap-2 data-[state=active]:bg-primary/20 data-[state=active]:text-primary">
            <Users className="h-4 w-4" />
            Employee Reports
            {unreadEmployeeCount > 0 && (
              <span className="ml-1 px-1.5 py-0.5 text-[10px] rounded-full bg-primary text-primary-foreground">{unreadEmployeeCount}</span>
            )}
          </TabsTrigger>
          <TabsTrigger value="insight" className="gap-2 data-[state=active]:bg-primary/20 data-[state=active]:text-primary">
            <Sparkles className="h-4 w-4" />
            AI Insights
            {unreadInsightCount > 0 && (
              <span className="ml-1 px-1.5 py-0.5 text-[10px] rounded-full bg-primary text-primary-foreground">{unreadInsightCount}</span>
            )}
          </TabsTrigger>
        </TabsList>

        <TabsContent value="employee" className="mt-6">
          <ReportsGrid reports={reports} isLoading={isLoading} onView={handleViewReport} onDelete={handleDeleteReport} emptyMessage="No employee reports yet. Your AI agents will add reports here." />
        </TabsContent>

        <TabsContent value="insight" className="mt-6">
          <ReportsGrid reports={activeTab === 'insight' ? reports : insightReports} isLoading={activeTab === 'insight' ? isLoading : loadingInsight} onView={handleViewReport} onDelete={handleDeleteReport} emptyMessage="No insights yet. Your AI agents will add insights here." />
        </TabsContent>
      </Tabs>

      <ReportViewerModal report={selectedReport} open={!!selectedReport} onOpenChange={(open) => !open && setSelectedReport(null)} />
    </div>
  );
};

interface ReportsGridProps {
  reports: Report[];
  isLoading: boolean;
  onView: (report: Report) => void;
  onDelete: (reportId: string) => void;
  emptyMessage: string;
}

const ReportsGrid = ({ reports, isLoading, onView, onDelete, emptyMessage }: ReportsGridProps) => {
  if (isLoading) return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;
  if (reports.length === 0) return (
    <div className="flex flex-col items-center justify-center py-20 text-center">
      <div className="p-4 rounded-full bg-muted/50 mb-4"><FileText className="h-12 w-12 text-muted-foreground" /></div>
      <p className="text-muted-foreground">{emptyMessage}</p>
    </div>
  );
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <AnimatePresence mode="popLayout">
        {reports.map((report) => <ReportCard key={report.id} report={report} onView={onView} onDelete={onDelete} />)}
      </AnimatePresence>
    </div>
  );
};
